steps:
  # Build the container image from project root
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:latest'
      - '-f'
      - 'creative-agent/Dockerfile'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:latest'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID,LOCATION=$_DEPLOY_REGION,STORAGE_BUCKET=$PROJECT_ID-assets,VIDEO_OUTPUT_GCS_BUCKET=$PROJECT_ID-assets/veo-output'
      - '--memory'
      - '2Gi'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '10'

images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:latest'

substitutions:
  _SERVICE_NAME: creative-agent
  _DEPLOY_REGION: us-central1  # Required for VEO 3.0 video generation
  _GCR_HOSTNAME: us.gcr.io
  _REPO_NAME: cloud-run-source-deploy

options:
  dynamicSubstitutions: true
